apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginext-deployment
  labels:
    app: loginextnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginextnginx
  template:
    metadata:
      labels:
        app: loginextnginx
    spec:
      containers:
      - name: loginextnginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
